version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3001:3000"
    environment:
      MICROCMS_API_TOKEN: ${MICROCMS_API_TOKEN}
      BIGQUERY_CREDENTIALS: ${BIGQUERY_CREDENTIALS}
    entrypoint: /app/entrypoint.sh
    command: yarn dev:server
    volumes:
      - ./:/app:cached
      - node-modules:/app/node_modules

volumes:
  node-modules: