name = "kiribi-survaq-api"
compatibility_date = "2024-04-03"
main = "src/tasks/index.ts"
node_compat = true

[[kv_namespaces]]
binding = "CACHE"
id = "e45d1964fa5549a484bf4b3855a46a90"

[[r2_buckets]]
binding = 'CMS_BUCKETS'
bucket_name = 'directus'

[[d1_databases]]
binding = "KIRIBI_DB"
database_name = "kiribi-db-survaq-api"
database_id = "d28400c7-6a48-4b90-a88a-32add61a1f4d"
migrations_dir = './node_modules/kiribi/migrations'

[[queues.producers]]
binding = "KIRIBI_QUEUE"
queue = "kiribi-queue-survaq-api"

[[queues.consumers]]
queue = "kiribi-queue-survaq-api"
max_retries = 5

[triggers]
# 1日に1回と1時間に1回
crons = [ "0 0 * * *", "0 * * * *", "*/10 * * * *" ]

[[services]]
binding = "KIRIBI"
service = "kiribi-survaq-api"

[[services]]
binding = "Cancel"
service = "kiribi-survaq-api"
entrypoint = "Cancel"

[[services]]
binding = "ProductSync"
service = "kiribi-survaq-api"
entrypoint = "ProductSync"

[[services]]
binding = "TransactionMailSend"
service = "kiribi-survaq-api"
entrypoint = "TransactionMailSend"

[[services]]
binding = "CompleteOrder"
service = "kiribi-survaq-api"
entrypoint = "CompleteOrder"

[[services]]
binding = "PurchaseMeasurementProtocol"
service = "kiribi-survaq-api"
entrypoint = "PurchaseMeasurementProtocol"

[[services]]
binding = "CMSChecker"
service = "kiribi-survaq-api"
entrypoint = "CMSChecker"

[[services]]
binding = "SyncShopifyOrderToBigQuery"
service = "kiribi-survaq-api"
entrypoint = "SyncShopifyOrderToBigQuery"

[site]
bucket = "./node_modules/kiribi/client"