name = "survaq-api-production"
main = "src/entry.ts"
compatibility_date = "2024-04-03"
node_compat = true

[[kv_namespaces]]
binding = "CACHE"
id = "e45d1964fa5549a484bf4b3855a46a90"

[[r2_buckets]]
binding = 'CMS_BUCKETS'
bucket_name = 'directus'

[site]
bucket = "./assets"

[[services]]
binding = "KIRIBI"
service = "kiribi-survaq-api"

[[services]]
binding = "CMSChecker"
service = "kiribi-survaq-api"
entrypoint = "CMSChecker"
