name = "survaq-api"
main = "src/entry.ts"
compatibility_date = "2023-12-07"
node_compat = true

[build]
command = "npm run build:wc"
watch_dir = "./src"

[site]
bucket = "./assets"

# devではhyperdriveが利用できなくなってしまった
# In development, you should use a local postgres connection string to emulate hyperdrive functionality.
# Please setup postgres locally and set the value of "HYPERDRIVE"'s "localConnectionString" to the postgres connection string in your wrangler.toml
#[[hyperdrive]]
#binding = "HYPERDRIVE"
#id = "b878be59a4024074b80a84e8c88a08cf"

[env.production]
name = "survaq-api-production"
hyperdrive=[{ binding = "HYPERDRIVE", id = "b878be59a4024074b80a84e8c88a08cf" }]

[env.preview]
name = "survaq-api-preview"
hyperdrive=[{ binding = "HYPERDRIVE", id = "b878be59a4024074b80a84e8c88a08cf" }]
